/** SKILLS */
export const const_skills = [
  {
    title: "Bash",
    url: "https://www.gnu.org/software/bash/",
    dark: "/images/skills/dark/bash.svg",
    light: "/images/skills/light/bash.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "C",
    url: "https://www.iso.org/standard/74528.html",
    dark: "/images/skills/universal/c.svg",
    light: "/images/skills/universal/c.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Cpp",
    url: "https://isocpp.org/",
    dark: "/images/skills/universal/cpp.svg",
    light: "/images/skills/universal/cpp.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "C#",
    url: "https://learn.microsoft.com/en-us/dotnet/csharp/",
    dark: "/images/skills/universal/csharp.svg",
    light: "/images/skills/universal/csharp.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "CSS",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    dark: "/images/skills/universal/css.svg",
    light: "/images/skills/universal/css.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Html",
    url: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    dark: "/images/skills/universal/html.svg",
    light: "/images/skills/universal/html.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Java",
    url: "https://www.oracle.com/java/",
    dark: "/images/skills/universal/java.avif",
    light: "/images/skills/universal/java.avif",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Javascript",
    url: "https://developer.mozilla.org/en-US/docs/Web/javascript",
    dark: "/images/skills/universal/javascript.png",
    light: "/images/skills/universal/javascript.png",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Kotlin",
    url: "https://kotlinlang.org/",
    dark: "/images/skills/universal/kotlin.svg",
    light: "/images/skills/universal/kotlin.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Python",
    url: "https://www.python.org/",
    dark: "/images/skills/universal/python.png",
    light: "/images/skills/universal/python.png",
    style: { width: "48px", height: "58px", margin: "0 4px" },
  },
  {
    title: "Typescript",
    url: "https://www.typescriptlang.org/",
    dark: "/images/skills/universal/ts.png",
    light: "/images/skills/universal/ts.png",
    style: { width: "58px", height: "58px", margin: "0 4px" },
  },
  {
    title: "React",
    url: "https://react.dev/",
    dark: "/images/skills/universal/react.png",
    light: "/images/skills/universal/react.png",
    style: { width: "58px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Material UI",
    url: "https://mui.com/",
    dark: "/images/skills/universal/material-ui.svg",
    light: "/images/skills/universal/material-ui.svg",
    style: { width: "58px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Node",
    url: "https://nodejs.org/",
    dark: "/images/skills/dark/node-js.svg",
    light: "/images/skills/light/node-js.svg",
    style: { width: "58px", height: "58px", margin: "0 4px" },
  },
  {
    title: "Next.js",
    url: "https://nextjs.org/",
    dark: "/images/skills/dark/nextjs.png",
    light: "/images/skills/light/nextjs.png",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Vite",
    url: "https://vitejs.dev/",
    dark: "/images/skills/universal/vitejs-logo.svg",
    light: "/images/skills/universal/vitejs-logo.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "NI TestStand",
    url: "https://www.ni.com/en/shop/electronic-test-instrumentation/application-software-for-electronic-test-and-instrumentation-category/what-is-teststand.html",
    dark: "/images/skills/universal/ni.png",
    light: "/images/skills/universal/ni.png",
    style: { width: "48px", height: "36px", margin: "0 4px" },
  },
  {
    title: "Cypress",
    url: "https://www.cypress.io/",
    dark: "/images/skills/dark/cypress.svg",
    light: "/images/skills/light/cypress.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Docker",
    url: "https://www.docker.com/",
    dark: "/images/skills/universal/docker.svg",
    light: "/images/skills/universal/docker.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Express",
    url: "https://expressjs.com/",
    dark: "/images/skills/dark/express.svg",
    light: "/images/skills/light/express.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Terraform",
    url: "https://www.terraform.io/",
    dark: "/images/skills/universal/terraform.svg",
    light: "/images/skills/universal/terraform.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Git",
    url: "https://git-scm.com/",
    dark: "/images/skills/universal/git.svg",
    light: "/images/skills/universal/git.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Visual Studio Code",
    url: "https://code.visualstudio.com/",
    dark: "/images/skills/universal/vscode.svg",
    light: "/images/skills/universal/vscode.svg",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Azure",
    url: "https://azure.microsoft.com/",
    dark: "/images/skills/universal/azure.png",
    light: "/images/skills/universal/azure.png",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "MongoDB",
    url: "https://www.mongodb.com/",
    dark: "/images/skills/universal/mongoDB.svg",
    light: "/images/skills/universal/mongoDB.svg",
    style: { width: "68px", height: "48px", margin: "0 4px" },
  },
  {
    title: "MySQL",
    url: "https://www.mysql.com/",
    dark: "/images/skills/universal/mysql.png",
    light: "/images/skills/universal/mysql.png",
    style: { width: "68px", height: "48px", margin: "0 4px" },
  },
  {
    title: "CSM",
    url: "https://scrumalliance.org",
    dark: "/images/skills/universal/csm.png",
    light: "/images/skills/universal/csm.png",
    style: { width: "48px", height: "48px", margin: "0 4px" },
  },
  {
    title: "Ubuntu",
    url: "https://ubuntu.com/",
    dark: "/images/skills/dark/ubuntu.svg",
    light: "/images/skills/light/ubuntu.svg",
    style: { width: "64px", height: "64px", margin: "0 4px" },
  },
];
